### ISSUE TITLE
Create Category Form Page

### ISSUE THREAD

**Issue by MarlenAw** [FACN3/easyRep#2]
The first page of the form will ask the users to select from a category list that describe possible environmental hazards.

 - [X] Create a clickable category list - list the type of complaints
 - [X] Each category should have it's own icon (we need to find good icons that are descriptive) and label.
 - [x] Depending on the chosen category, it needs to sort the proper descriptions (ex: burning eyes because of smoke..) on the next page.

**Comment by MynahMarie** [comment]
Can we close this issue?
