### ISSUE TITLE
Create a Login button

### ISSUE THREAD

**Issue by MarlenAw** [FACN3/easyRep#5]
Duplicate of #9 #11 

As a user I would like to:

  - Be able to sign in into my account using Facebook or Google.

Acceptance criteria: 

  - [ ] Login button
  - [ ] Facebook/Google Authentication

**Comment by MynahMarie** [comment]
I thought we would do the login in Stage 2 through the "View Reports" button? Is that still the idea?

Anyway I'm labeling this as duplicate because we already have a god stage 2 user story in which authentication is included.

**Comment by MarlenAw** [comment]
We should close this issue since we already have it in Stage 2. 
It's best if we don't have duplicate issues.

If both of you agree @hoslack  @MynahMarie  , then I can close it.
